# Generated by Django 3.2.13 on 2025-06-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20250604_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocol',
            name='file',
        ),
        migrations.AddField(
            model_name='protocol',
            name='drilling_supervisor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='drilling_system',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='expansion_sequence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='location_system',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='rod_length',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='site_supervisor',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='total_length',
            field=models.FloatField(null=True),
        ),
    ]
